version: "3.8"

networks:
  platform:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.6.0.0/24

services:
  python:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      platform:
        ipv4_address: 10.6.0.10
    ports:
      - 8000:8000
    restart: always
    volumes:
      - "./:/opt/app-root/app:cached"
